apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhte2023
  namespace: rhte
spec:
  destination:
    namespace: rhte
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/ipilcher/rhte2023.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
